// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wipro.core.Data.Context;

namespace wipro.core.Migrations
{
    [DbContext(typeof(wpContext))]
    [Migration("20210609140127_Checked")]
    partial class Checked
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("wipro.core.Model.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Moeda");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Simbolo = "USD"
                        },
                        new
                        {
                            Id = 2,
                            Simbolo = "PGK"
                        },
                        new
                        {
                            Id = 3,
                            Simbolo = "ARS"
                        },
                        new
                        {
                            Id = 4,
                            Simbolo = "LSL"
                        },
                        new
                        {
                            Id = 5,
                            Simbolo = "RON"
                        },
                        new
                        {
                            Id = 6,
                            Simbolo = "AWG"
                        },
                        new
                        {
                            Id = 7,
                            Simbolo = "MUR"
                        },
                        new
                        {
                            Id = 8,
                            Simbolo = "CUP"
                        },
                        new
                        {
                            Id = 9,
                            Simbolo = "JPY"
                        },
                        new
                        {
                            Id = 10,
                            Simbolo = "SLL"
                        },
                        new
                        {
                            Id = 11,
                            Simbolo = "ISK"
                        },
                        new
                        {
                            Id = 12,
                            Simbolo = "EGP"
                        },
                        new
                        {
                            Id = 13,
                            Simbolo = "TRY"
                        },
                        new
                        {
                            Id = 14,
                            Simbolo = "XOF"
                        },
                        new
                        {
                            Id = 15,
                            Simbolo = "MRU"
                        },
                        new
                        {
                            Id = 16,
                            Simbolo = "CLP"
                        },
                        new
                        {
                            Id = 17,
                            Simbolo = "IRR"
                        },
                        new
                        {
                            Id = 18,
                            Simbolo = "GIP"
                        },
                        new
                        {
                            Id = 19,
                            Simbolo = "KMF"
                        },
                        new
                        {
                            Id = 20,
                            Simbolo = "EUR"
                        },
                        new
                        {
                            Id = 21,
                            Simbolo = "KES"
                        },
                        new
                        {
                            Id = 22,
                            Simbolo = "GBP"
                        },
                        new
                        {
                            Id = 23,
                            Simbolo = "NIO"
                        },
                        new
                        {
                            Id = 24,
                            Simbolo = "PHP"
                        },
                        new
                        {
                            Id = 25,
                            Simbolo = "CAD"
                        },
                        new
                        {
                            Id = 26,
                            Simbolo = "MGB"
                        },
                        new
                        {
                            Id = 27,
                            Simbolo = "XDR"
                        },
                        new
                        {
                            Id = 28,
                            Simbolo = "WST"
                        },
                        new
                        {
                            Id = 29,
                            Simbolo = "CZK"
                        },
                        new
                        {
                            Id = 30,
                            Simbolo = "XAF"
                        },
                        new
                        {
                            Id = 31,
                            Simbolo = "ZWL"
                        },
                        new
                        {
                            Id = 32,
                            Simbolo = "SBD"
                        },
                        new
                        {
                            Id = 33,
                            Simbolo = "ANG"
                        },
                        new
                        {
                            Id = 34,
                            Simbolo = "OMR"
                        },
                        new
                        {
                            Id = 35,
                            Simbolo = "MGA"
                        },
                        new
                        {
                            Id = 36,
                            Simbolo = "DJF"
                        },
                        new
                        {
                            Id = 37,
                            Simbolo = "COP"
                        },
                        new
                        {
                            Id = 38,
                            Simbolo = "FJD"
                        },
                        new
                        {
                            Id = 39,
                            Simbolo = "THB"
                        },
                        new
                        {
                            Id = 40,
                            Simbolo = "ILS"
                        },
                        new
                        {
                            Id = 41,
                            Simbolo = "MXN"
                        },
                        new
                        {
                            Id = 42,
                            Simbolo = "LBP"
                        },
                        new
                        {
                            Id = 43,
                            Simbolo = "MZN"
                        },
                        new
                        {
                            Id = 44,
                            Simbolo = "SAR"
                        },
                        new
                        {
                            Id = 45,
                            Simbolo = "PEN"
                        },
                        new
                        {
                            Id = 46,
                            Simbolo = "UYU"
                        },
                        new
                        {
                            Id = 47,
                            Simbolo = "SSP"
                        },
                        new
                        {
                            Id = 48,
                            Simbolo = "GEL"
                        },
                        new
                        {
                            Id = 49,
                            Simbolo = "ALL"
                        },
                        new
                        {
                            Id = 50,
                            Simbolo = "XPF"
                        },
                        new
                        {
                            Id = 51,
                            Simbolo = "CVE"
                        },
                        new
                        {
                            Id = 52,
                            Simbolo = "CRC"
                        },
                        new
                        {
                            Id = 53,
                            Simbolo = "MRO"
                        },
                        new
                        {
                            Id = 54,
                            Simbolo = "DZD"
                        },
                        new
                        {
                            Id = 55,
                            Simbolo = "SZL"
                        },
                        new
                        {
                            Id = 56,
                            Simbolo = "BOB"
                        },
                        new
                        {
                            Id = 57,
                            Simbolo = "VUV"
                        },
                        new
                        {
                            Id = 58,
                            Simbolo = "CDF"
                        },
                        new
                        {
                            Id = 59,
                            Simbolo = "UGX"
                        },
                        new
                        {
                            Id = 60,
                            Simbolo = "XAU"
                        },
                        new
                        {
                            Id = 61,
                            Simbolo = "SOS"
                        },
                        new
                        {
                            Id = 62,
                            Simbolo = "NOK"
                        },
                        new
                        {
                            Id = 63,
                            Simbolo = "HTG"
                        },
                        new
                        {
                            Id = 64,
                            Simbolo = "BYN"
                        },
                        new
                        {
                            Id = 65,
                            Simbolo = "ZAR"
                        },
                        new
                        {
                            Id = 66,
                            Simbolo = "AFN"
                        },
                        new
                        {
                            Id = 67,
                            Simbolo = "TTD"
                        },
                        new
                        {
                            Id = 68,
                            Simbolo = "VES"
                        },
                        new
                        {
                            Id = 69,
                            Simbolo = "MMK"
                        },
                        new
                        {
                            Id = 70,
                            Simbolo = "SGD"
                        });
                });

            modelBuilder.Entity("wipro.core.Model.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Fim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime");

                    b.Property<int?>("MoedaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoedaId");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("wipro.core.Model.Processo", b =>
                {
                    b.HasOne("wipro.core.Model.Moeda", "Moeda")
                        .WithMany()
                        .HasForeignKey("MoedaId");

                    b.Navigation("Moeda");
                });
#pragma warning restore 612, 618
        }
    }
}
